spring:
  datasource:
    username: root
    password: su360595304
    url: jdbc:mysql://localhost:3306/bookstore
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT%2B8

mybatis-plus:
  type-aliases-package: com.hu.bookstore.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/hu/bookstore/mapper/*Mapper.xml