spring:
  datasource:
    username: root
    password: su360595304
    url: jdbc:mysql://localhost:3306/bookstore
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  type-aliases-package: com.hu.bookstore.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl